export const GET_ALL_COLORS = 'GET_ALL_COLORS';
export const GET_ALL_COLORS_SUCCESS = 'GET_ALL_COLORS_SUCCESS';
export const GET_ALL_COLORS_FAILURE = 'GET_ALL_COLORS_FAILURE';

export const BACKGROUND_COLOR = 'BACKGROUND_COLOR';
export const SELECTED_COLOR = 'SELECTED_COLOR';

export const SHOW_COLOR_LIST = 'SHOW_COLOR_LIST';
export const HIDE_COLOR_LIST = 'HIDE_COLOR_LIST';